#!/bin/bash

# A lazy way to convert special chars from given list, usual for name lists.

sed -iE  's,\á,a,g' brazilian-names-and-gender.csv
sed -iE  's,\é,e,g' brazilian-names-and-gender.csv
sed -iE  's,\í,i,g' brazilian-names-and-gender.csv
sed -iE  's,\ó,o,g' brazilian-names-and-gender.csv
sed -iE  's,\ú,u,g' brazilian-names-and-gender.csv
sed -iE  's,\â,a,g' brazilian-names-and-gender.csv
sed -iE  's,\ê,e,g' brazilian-names-and-gender.csv
sed -iE  's,\î,i,g' brazilian-names-and-gender.csv
sed -iE  's,\ô,o,g' brazilian-names-and-gender.csv
sed -iE  's,\û,u,g' brazilian-names-and-gender.csv
sed -iE  's,\à,a,g' brazilian-names-and-gender.csv
sed -iE  's,\è,e,g' brazilian-names-and-gender.csv
sed -iE  's,\ì,i,g' brazilian-names-and-gender.csv
sed -iE  's,\ò,o,g' brazilian-names-and-gender.csv
sed -iE  's,\ù,u,g' brazilian-names-and-gender.csv
sed -iE  's,\ä,a,g' brazilian-names-and-gender.csv
sed -iE  's,\ë,e,g' brazilian-names-and-gender.csv
sed -iE  's,\ï,i,g' brazilian-names-and-gender.csv
sed -iE  's,\ö,o,g' brazilian-names-and-gender.csv
sed -iE  's,\ü,u,g' brazilian-names-and-gender.csv
sed -iE  's,\ã,a,g' brazilian-names-and-gender.csv
sed -iE  's,\õ,o,g' brazilian-names-and-gender.csv
sed -iE  's,\ñ,n,g' brazilian-names-and-gender.csv
sed -iE  's,\ç,c,g' brazilian-names-and-gender.csv
sed -iE 's,Á,a,g' brazilian-names-and-gender.csv
sed -iE 's,É,e,g' brazilian-names-and-gender.csv
sed -iE 's,Í,i,g' brazilian-names-and-gender.csv
sed -iE 's,Ó,o,g' brazilian-names-and-gender.csv
sed -iE 's,Ú,u,g' brazilian-names-and-gender.csv
sed -iE 's,Â,a,g' brazilian-names-and-gender.csv
sed -iE 's,Ê,e,g' brazilian-names-and-gender.csv
sed -iE 's,Î,i,g' brazilian-names-and-gender.csv
sed -iE 's,Ô,o,g' brazilian-names-and-gender.csv
sed -iE 's,Û,u,g' brazilian-names-and-gender.csv
sed -iE 's,À,a,g' brazilian-names-and-gender.csv
sed -iE 's,È,e,g' brazilian-names-and-gender.csv
sed -iE 's,Ì,i,g' brazilian-names-and-gender.csv
sed -iE 's,Ò,o,g' brazilian-names-and-gender.csv
sed -iE 's,Ù,u,g' brazilian-names-and-gender.csv
sed -iE 's,Ä,a,g' brazilian-names-and-gender.csv
sed -iE 's,Ë,e,g' brazilian-names-and-gender.csv
sed -iE 's,Ï,i,g' brazilian-names-and-gender.csv
sed -iE 's,Ö,o,g' brazilian-names-and-gender.csv
sed -iE 's,Ü,u,g' brazilian-names-and-gender.csv
sed -iE 's,Ã,a,g' brazilian-names-and-gender.csv
sed -iE 's,Õ,o,g' brazilian-names-and-gender.csv
sed -iE 's,Ñ,n,g' brazilian-names-and-gender.csv
sed -iE 's,Ç,c,g' brazilian-names-and-gender.csv
